### ISSUE TITLE
CC Menu doesn't attempt to login if some results are visible without authentication

### ISSUE THREAD

**Issue by alanbirtles** [erikdoe/ccmenu#96] opened 2018-03-15 14:56 UTC
We have a hudson server which is configured in such a way that downloading cc.xml with no authentication succeeds but returns an empty project list.
In this case CCMenu just downloads the empty list and never attempts to authenticate even when "The server requires authentication" is checked

**Comment by erikdoe** [comment] 2018-04-05 20:15
Closing this as a duplicate of #72.

**Closed by erikdoe** 2018-04-05 20:15 UTC
